[package]
name = "emulator"
version = "0.1.0"
edition = "2021"

[dependencies]
blt = { path = "../blt" }
anyhow = "1.0.52"
tokio = { version = "1.15.0", features = ["rt-multi-thread", "macros", "io-util", "io-std"] }
bluer = "0.13.1"
uuid = { version = "0.8.2", features = ["v4"] }